### ISSUE TITLE
AlmaLinux9

### ISSUE THREAD

**Issue by aleksandr-kosobokov** [tcler/kiss-vm-ns#4]
Dear team kiss-vm-ns thank you for the cool tool!

Please could you point me or add support kiss-vm-ns on alma9

thanks

**Comment by tcler** [comment]
Hi, friend:  
  alma-linux-9 has been there.

```
commit c7132b8300d3b07ab180c8fe5be3763c6c9c11ff
Author: Jianhong Yin <yin-jianhong@163.com>
Date:   Tue Nov 21 15:52:18 2023 +0800

    update distro-db: add Alma-linux and update FreeBSD version
    
    Signed-off-by: Jianhong Yin <yin-jianhong@163.com>
```

just run **kiss-update.sh** and type follow command to create VM based on Alma-9:  
```
vm create Alma-9 -n $vmname [other options]
```

**Comment by tcler** [comment]
> Dear team kiss-vm-ns thank you for the cool tool!
> 
> Please could you point me or add support kiss-vm-ns on alma9

kiss-vm-ns works fine on RHEL-9, so it should work on alma9. please have a try.  
feel free to contact to me if encounter any problem

> 
> thanks
